### ISSUE TITLE
想推荐你这个项目

### ISSUE THREAD

**Issue by polaris1119** [GuoZhaoran/spikeSystem#1]
大佬你好，我是Go语言中文网（https://studygolang.com ）站长，看到你这个项目，很赞，我想分享给更多的 Go 语言爱好者。特向你申请授权我发布到网站和对应的公众号等渠道。因为会大量引用README中的内容，期待您的回复！谢谢！

**Comment by GuoZhaoran** [comment]
可以推荐，要加上转载来源。




------------------ 原始邮件 ------------------
发件人: "徐新华"<notifications@github.com>;
发送时间: 2019年10月17日(星期四) 晚上7:42
收件人: "GuoZhaoran/spikeSystem"<spikeSystem@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [GuoZhaoran/spikeSystem] 想推荐你这个项目 (#1)




大佬你好，我是Go语言中文网（https://studygolang.com）站长，看到你这个项目，很赞，我想分享给更多的 Go 语言爱好者。特向你申请授权我发布到网站和对应的公众号等渠道。因为会大量引用README中的内容，期待您的回复！谢谢！

**Comment by polaris1119** [comment]
那是肯定

**Comment by shunhua** [comment]
> 大佬你好，我是Go语言中文网（https://studygolang.com ）站长，看到你这个项目，很赞，我想分享给更多的 Go 语言爱好者。特向你申请授权我发布到网站和对应的公众号等渠道。因为会大量引用README中的内容，期待您的回复！谢谢！

你这网站 很爱转圈圈哈。
